### ISSUE TITLE
Missing Pointers for Benthic Fluxes in Direct Sinking of Phytoplankton P

### ISSUE THREAD

**Issue by yichengt900** [NOAA-CEFI-Regional-Ocean-Modeling/ocean_BGC#18]
In the recent code review, we discovered that the pointers for the benthic fluxes for the direct sinking of phytoplankton P were not correctly set in the `generic_COBALT_update_from_bottom` subroutine. This may be one reason why our P budget analysis cannot be closed. Additionally, this discovery motivates us to reconsider our current imbalance check approach, as it may not detect issues occurring outside the COBALT modules.

This issue is being raised on behalf of @charliestock.

**Comment by charliestock** [comment]
Thank you for handling this Yi-Cheng,  The net effect of this was a small amount of unintended phosphate burial.  This issue only impacts COBALTv3.0 and does not effect past versions of COBALT (for which phytoplankton sinking was not specified).  Furthermore, the unintended P burial was fortunately very small and did not create areas of P limitation.
