### ISSUE TITLE
cleanup: please consider deleting some old modules

### ISSUE THREAD

**Issue by nikizadehgfdl** [NOAA-CEFI-Regional-Ocean-Modeling/ocean_BGC#21]
Some of the generic modules are very old and have not been tested for a long time and probably won't work with MOM6 anymore. They just add to the compilation process load and time.
These include
generic_ERGOM.F90
generic_miniBLING.F90
generic_TOPAZ.F90

Please consider removing them.

**Comment by yichengt900** [comment]
@charliestock, as @nikizadehgfdl suggested, do you think it's safe to remove ERGOM, miniBLING, and TOPAZ since no one uses them anymore?
