### ISSUE TITLE
Legacy MOM4/5 ntau = tau can be removed?

### ISSUE THREAD

**Issue by charliestock** [NOAA-CEFI-Regional-Ocean-Modeling/ocean_BGC#26]
Calls to g_tracer_get_values currently specify a time step (i.e., ntau = tau).   

    call g_tracer_get_values(tracer_list,'cadet_arag','field',cobalt%f_cadet_arag ,isd,jsd,ntau=tau,positive=.true.)

I understand that this is a legacy from MOM4/5 and now ntau is always 1.  Perhaps we could simplify this?

**Comment by andrew-c-ross** [comment]
tau is also optional and defaults to 1 in generic tracer utils, so this can be safely removed from generic COBALT.

https://github.com/NOAA-CEFI-Regional-Ocean-Modeling/ocean_BGC/blob/5967e5b284f21c4f9c9fb0d8db295fed080d874f/generic_tracers/generic_tracer_utils.F90#L1883-L1904
