### ISSUE TITLE
Consistent/better way to handle COBALT runtime parameters?

### ISSUE THREAD

**Issue by yichengt900** [NOAA-CEFI-Regional-Ocean-Modeling/ocean_BGC#30]
We have been using both the `namelist` and `user_add_params` subroutine to define COBALT runtime parameters. To improve consistency in handling these parameters, we are considering moving all `namelist` parameters into `user_add_params`.

Furthermore, we should start considering a better approach to handle input runtime parameters. Given our timeline, the low-hanging fruit would be:

1. Continuing to use `user_add_params` and adding additional parameter output for sanity checks. We would also add our recommended values for the parameters in the field_table.

2. Borrowing existing functions/subroutines from MOM6. This would make COBALT input consistent with MOM6 but would add additional dependencies.

Update:

After discussing with @theresa-morrison, our plan will be to make this simple stdout function live for users to start using it for parameter sanity checks. Meanwhile, @theresa-morrison will begin bringing blank MOM6-type parameter inputs/outputs. In the short to medium term, both methods will co-exist. This approach will give us time to transition gradually towards MOM6-type parameter input and output.

**Comment by theresa-cordero** [comment]
PR #59 addresses this issue by adding COBALT parameter files.
