### ISSUE TITLE
Backward COBALTv2 compatibility discussion

### ISSUE THREAD

**Issue by charliestock** [NOAA-CEFI-Regional-Ocean-Modeling/ocean_BGC#34]
Hi folks,

Thanks for everyone's efforts with the code cleanup and improvements!

One issue that has come up in a number of issues and pull requests is backward compatibility with COBALTv2.  On the one hand, I would very much like to forge ahead toward COBALTv3 and I don't want to clutter things up with multiple interface options/etc.  On the other, there are still a number of folks running COBALTv2 for comparisons with past ESM4.1 runs, etc.  Colleagues from Woods Hole, for example, are downscaling ESM4.1 for a iron fertilization project.  They are leveraging CEFI tools to put together an initial configuration in the North Pacific and will need to use COBALTv2 for consistency with the global run they are downscaling.

Does anyone have any thoughts on the best procedure for cases like this?

Thanks,
Charlie

**Comment by yichengt900** [comment]
@charliestock , my suggestion is to create a feature branch in our  [CEFI-regional-MOM6](https://github.com/NOAA-GFDL/CEFI-regional-MOM6) repository that incorporates the latest MOM6 with OBC fixes. As for the ocean_BGC submodule, we can update it to point to the COBALTv2 branch.
