### ISSUE TITLE
Unneeded tracer id variables in generic_COBALT_type

### ISSUE THREAD

**Issue by charliestock** [NOAA-CEFI-Regional-Ocean-Modeling/ocean_BGC#37]
There are a number of diagnostic id's in the generic_COBALT_type for defined COBALT tracers.  These appear to be unused and I don't believe that we need them since the generic_tracer routines should handle these.  They can be found on:

https://github.com/NOAA-CEFI-Regional-Ocean-Modeling/ocean_BGC/blob/e499f4caa67d9ce358b08c3ff9d87e6ba521352d/generic_tracers/generic_COBALT.F90#L1160-L1199

https://github.com/NOAA-CEFI-Regional-Ocean-Modeling/ocean_BGC/blob/e499f4caa67d9ce358b08c3ff9d87e6ba521352d/generic_tracers/generic_COBALT.F90#L1215-L1217

I think the some of the btf id's can also be removed.  

It would be good to clarify with Niki which prognostic and diagnostic tracer variables are automatically registered.  I suspect this cleanup may eliminate around 100 lines or so.

**Comment by yichengt900** [comment]
I did a quick check on all the diagnostic id's in the generic_COBALT_type, and the following are unused currently in the code:
```
id_ndi
id_nlg
id_nmd
id_nsm
id_nsmz
id_nmdz
id_nlgz
id_nbact
id_alk
id_cadet_arag
id_cadet_calc
id_dic
id_fed
id_fedet
id_fedi
id_felg
id_femd
id_fesm
id_pdi
id_plg
id_pmd
id_psm
id_ldon
id_ldop
id_lith
id_lithdet
id_ndet
id_nh4
id_no3
id_o2
id_pdet
id_po4
id_srdop
id_srdon
id_sldon
id_sldop
id_sidet
id_silg
id_simd
id_sio4
id_chl
id_co3_ion
id_htotal
id_irr_mem_dp
id_cased
id_cadet_arag_btf
id_cadet_calc_btf
id_fedet_btf
id_lithdet_btf
id_ndet_btf
id_pdet_btf
id_sidet_btf
id_det_jzloss_p
id_det_jzloss_fe
id_det_jzloss_si
id_det_jhploss_p
id_det_jhploss_fe
id_det_jhploss_si
id_hp_jingest_n
id_hp_jingest_p
id_hp_jingest_fe
id_hp_jingest_sio2
id_di14c
id_do14c
!          id_o2min              = -1, &  ! previously defined
```
We could consider to remove them.
