### ISSUE TITLE
3D arrays used for 2D bottom flux and sediment storage "tracers"?

### ISSUE THREAD

**Issue by charliestock** [NOAA-CEFI-Regional-Ocean-Modeling/ocean_BGC#38]
I believe that generic tracers is currently passing bottom flux information as a 3D tracers but these are 2D variables.  The potential expense of this has been compounded by the addition of many new variables with boundary fluxes:

https://github.com/NOAA-CEFI-Regional-Ocean-Modeling/ocean_BGC/blob/e499f4caa67d9ce358b08c3ff9d87e6ba521352d/generic_tracers/generic_COBALT.F90#L7254-L7418

Niki, am I correct on this?  If so, could we make the code more memory efficient by allowing for 2D tracers?  How difficult do you think this would be?

Thanks,
Charlie

**Comment by yichengt900** [comment]
#46 is merged. Close this issue now.

**Comment by yichengt900** [comment]
Based on today's discussion, I will revert the `bottom flux 3d to 2d change` for now. We will reconsider once we have a better idea of its impact on the restart file.

**Comment by yichengt900** [comment]
After further investigation, this may require some infrastructure changes. Since the memory impact of converting sediment from 3D to 2D is not that significant in the current COBALT, we will close this issue for now.
