### ISSUE TITLE
Divide by zero in iceberg sources

### ISSUE THREAD

**Issue by andrew-c-ross** [NOAA-CEFI-Regional-Ocean-Modeling/ocean_BGC#5]
The 4P version of COBALT has the following lines [here](https://github.com/NOAA-CEFI-Regional-Ocean-Modeling/ocean_BGC/blob/3db75ef0f3939a85e129e98802097e45666ca337/generic_tracers/generic_COBALT.F90#L9768-L9770): 

```
cobalt%jfe_iceberg(i,j,1) = cobalt%jfe_iceberg_ratio*max(frunoff(i,j),0.0)/rho_dzt(i,j,1)
cobalt%jno3_iceberg(i,j,1) = cobalt%jno3_iceberg_ratio*max(frunoff(i,j),0.0)/rho_dzt(i,j,1)
cobalt%jpo4_iceberg(i,j,1) = cobalt%jpo4_iceberg_ratio*max(frunoff(i,j),0.0)/rho_dzt(i,j,1)

```

The problem is that `rho_dzt(:, :, 1)` (density times layer thickness) is 0 over land. 

This block probably needs to be wrapped in a check for the index of the bottom layer like  [line 9788](https://github.com/NOAA-CEFI-Regional-Ocean-Modeling/ocean_BGC/blob/3db75ef0f3939a85e129e98802097e45666ca337/generic_tracers/generic_COBALT.F90#L9788C8-L9788C38):
```
if (grid_kmt(i,j) .gt. 0) then
```

I don't think this affects the solution since it happens over land, but debugging other issues (like I'm currently trying to do) is harder since the model aborts here when it is compiled in debug mode.

**Comment by yichengt900** [comment]
Thanks, @andrew-c-ross, for reporting this bug. I can open a pull request to hotfix this issue if you prefer.
