### ISSUE TITLE
Configuring SSH for Repository Cloning

### ISSUE THREAD

**Issue by feida6996** [NOAA-CEFI-Regional-Ocean-Modeling/ocean_BGC#52]
After following Yi-Cheng's [tutorial](https://github.com/NOAA-CEFI-Regional-Ocean-Modeling/ocean_BGC/wiki/How-to-clone,-create-branch,-commit-changes,-push-changes,-and-open-a-pull-request#00--generating-ssh-key-and-add-to-your-github-account-optional) on cloning a repository (step 1.1), I realized that certain configuration settings were necessary in the SSH configuration file on Gaea if I want to use SSH approach rather than HTTP. This might be specific to my setup, but I thought I'd share in case others encounter similar issues. 

You may need to add the following to /ncrc/home1/XX.XX/.ssh/config

_\# START GitHub SSH key
Host github.com
  HostName github.com
  User git
  IdentityFile ~/.ssh/id_rsa_git
\# END GitHub SSH key_

Note: Because I already have SSH keys created previously (id_rsa), id_rsa_git is the custom-named SSH key created from step 0.0 of the [tutorial](https://github.com/NOAA-CEFI-Regional-Ocean-Modeling/ocean_BGC/wiki/How-to-clone,-create-branch,-commit-changes,-push-changes,-and-open-a-pull-request). You may change the name of the key based on your preference.

**Comment by yichengt900** [comment]
@feida6996, thank you for the additions. I will include this in our tutorial.

**Comment by yichengt900** [comment]
Have added this tips to our [wiki page](https://github.com/NOAA-CEFI-Regional-Ocean-Modeling/ocean_BGC/wiki/How-to-clone,-create-branch,-commit-changes,-push-changes,-and-open-a-pull-request#add-ssh-key-to-your-github-account). Close this issue for now.
