### ISSUE TITLE
Removing the "ocmip2" option?

### ISSUE THREAD

**Issue by charliestock** [NOAA-CEFI-Regional-Ocean-Modeling/ocean_BGC#71]
In a prior meeting, the potential removal of the "ocmip2" option for carbon system calculations was raised.  This is technically the default setting for carbon system calculations but it is never used as far as I am aware.   John Dunne's comments also seemed to imply that it was clearly inferior to mocsy.  I have sent an e-mail to John to confirm his view on this.  If it does prove to be the case, there seems to be a significant opportunity to simplify and shorten the code here.  A few thoughts:

1. We could retain https://github.com/NOAA-CEFI-Regional-Ocean-Modeling/ocean_BGC/blob/dev/cefi/generic_tracers/FMS_ocmip2_co2calc.F90 or move it to FMS_ocmip2_co2calc.F90.archive to preserve this structure for some period of time (I suspect several other routines may still use it.

2. We could create FMS_co2calc.F90 from this routine by reducing it to a "mocsy" interface.

3. We could remove the co2_calc option.

4. The following sections of generic_COBALT.F90 could be removed and/or simplified:
https://github.com/NOAA-CEFI-Regional-Ocean-Modeling/ocean_BGC/blob/b1dd5ecc7a85398eee8f63861381eabf75926edd/generic_tracers/generic_COBALT.F90#L101-L105
https://github.com/NOAA-CEFI-Regional-Ocean-Modeling/ocean_BGC/blob/b1dd5ecc7a85398eee8f63861381eabf75926edd/generic_tracers/generic_COBALT.F90#L274-L280
https://github.com/NOAA-CEFI-Regional-Ocean-Modeling/ocean_BGC/blob/b1dd5ecc7a85398eee8f63861381eabf75926edd/generic_tracers/generic_COBALT.F90#L2353-L2394
https://github.com/NOAA-CEFI-Regional-Ocean-Modeling/ocean_BGC/blob/b1dd5ecc7a85398eee8f63861381eabf75926edd/generic_tracers/generic_COBALT.F90#L3876-L3900
https://github.com/NOAA-CEFI-Regional-Ocean-Modeling/ocean_BGC/blob/b1dd5ecc7a85398eee8f63861381eabf75926edd/generic_tracers/generic_COBALT.F90#L5972-L6000

Thoughts?  @yichengt900 @jessluo @gabyneg?

**Comment by yichengt900** [comment]
PR #72 solved this issue. Close now.
